%% Atualiza os valores das constantes para os valores digitados

% Erro máximo da orientação (em graus) e da posição (em mm)
Constantes.Erro = [str2double(TelaConstantes.Valor(1).String) ...
                   str2double(TelaConstantes.Valor(2).String)];

% Constantes de saturação da velocidade
Constantes.Saturacao = [str2double(TelaConstantes.Valor(3).String) ...
                        str2double(TelaConstantes.Valor(4).String); ...
                        str2double(TelaConstantes.Valor(5).String) ...
                        str2double(TelaConstantes.Valor(6).String)];

% Constantes do comportamento da curva de velocidade
Constantes.Curva = [str2double(TelaConstantes.Valor(7).String) ...
                    str2double(TelaConstantes.Valor(8).String); ...
                    str2double(TelaConstantes.Valor(9).String) ...
                    str2double(TelaConstantes.Valor(10).String)];

% Tempo de máximo para atualizar cada setor
Constantes.TmaxPartida = str2double(TelaConstantes.Valor(11).String)/1000;
Constantes.TmaxRobos   = str2double(TelaConstantes.Valor(12).String)/1000;
Constantes.TmaxResult  = str2double(TelaConstantes.Valor(13).String)/1000;

% Ganho das rodas: As linhas representam cada Robô e as colunas as rodas esquerda e direita
Constantes.Ganho = [str2double(TelaConstantes.Valor(14).String) ...
                    str2double(TelaConstantes.Valor(15).String); ...
                    str2double(TelaConstantes.Valor(16).String) ...
                    str2double(TelaConstantes.Valor(17).String); ...
                    str2double(TelaConstantes.Valor(18).String) ...
                    str2double(TelaConstantes.Valor(19).String)];